import "../styles/Patient.css";

const formatDateTime = (iso) => {
  if (!iso) return "N/A";
  const d = new Date(iso);
  return d.toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

function PatientMedicalRecords({ user, patient }) {
  if (!patient) {
    return (
      <div className="profile-box">
        <h3>Medical Records</h3>
        <div className="record-card">
          No patient selected.
        </div>
      </div>
    );
  }

  const records = patient.medicalHistory || [];

  return (
    <div className="profile-box animate-fade-in">
      <h2>Medical Records Generated by AI</h2>

      {/* Patient Summary */}
      <div className="selection-summary">
        <div>
          <strong>{user?.name}</strong>
          <div className="doctor-subtext">{user?.email}</div>
        </div>

        <div className="appt-meta">
          <span>Age: {patient.age}</span>
          <span>Gender: {patient.gender}</span>
          <span>Mobile No.: {patient.mobile}</span>
        </div>
      </div>

      {records.length === 0 ? (
        <div className="empty-list-msg">
          No medical records available for this patient.
        </div>
      ) : (
        records
          .slice()
          .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))
          .map((record, index) => (
            <div key={index} className="bill-group animate-fade-in">
              
              {/* Header */}
              <div className="bill-group-header">

                <span className="bill-date">
                  {formatDateTime(record.createdAt)}
                </span>
              </div>

              {/* Details */}
              <div className="bill-details-list">
                <div className="bill-item-row">
                  <div className="bill-main">
                    <strong>Diagnosis</strong>
                    <span className="doctor-subtext">
                      {record.diagnosis || "Not specified"}
                    </span>
                  </div>
                </div>

                <div className="bill-item-row">
                  <div className="bill-main">
                    <strong>Prescription</strong>
                    <span className="doctor-subtext">
                      {record.prescription || "Not specified"}
                    </span>
                  </div>
                </div>

                {/* Image Attachments */}
                {record.fileUrls && record.fileUrls.length > 0 && (
                  <div className="bill-item-row">
                    <div className="bill-main">
                      <strong>Reports / Images</strong>

                      <div className="medical-image-grid">
                        {record.fileUrls.map((url, i) => (
                          <img
                            key={i}
                            src={url}
                            alt={`Medical report ${i + 1}`}
                            className="medical-thumb"
                            onClick={() => window.open(url, "_blank")}
                          />
                        ))}
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          ))
      )}
    </div>
  );
}

export default PatientMedicalRecords;