spring.application.name=eHealth
server.port=${SERVER_PORT:8080}

# MongoDB
spring.mongodb.uri=${MONGO_URI}
spring.data.mongodb.auto-index-creation=true

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App config
app.is-production=${APP_IS_PRODUCTION:false}

# Cloudinary
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${CLOUD_API_KEY}
cloudinary.api-secret=${CLOUD_API_SECRET}

# WebRTC (signaling only - safe to leave hardcoded as it uses a public Google stun server)
webrtc.stun.server=stun:stun.l.google.com:19302

# 1. Specify the name and location of the text file
logging.file.name=${LOGGING_FILE_NAME:logs/ehealth-requests.txt}
# 2. Set the logging format for the file (Optional, but makes it cleaner)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# 3. Ensure your custom interceptor is logging at the INFO level
logging.level.com.eHealth.eHealth.config.ControllerLoggingInterceptor=INFO 




//

spring.application.name=eHealth
server.port=${SERVER_PORT:8080}


# MongoDB
spring.mongodb.uri=${MONGO_URI}
spring.data.mongodb.auto-index-creation=true


# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# App config
app.is-production=${APP_IS_PRODUCTION:false}


# Cloudinary
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${CLOUD_API_KEY}
cloudinary.api-secret=${CLOUD_API_SECRET}


# WebRTC (signaling only - safe to leave hardcoded as it uses a public Google stun server)
webrtc.stun.server=stun:stun.l.google.com:19302
